# Generated by Django 5.2 on 2025-06-30 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalia',
            fields=[
                ('id_avalia', models.AutoField(primary_key=True, serialize=False)),
                ('valor_avalia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('matricula_perfil', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_postagem', models.CharField(max_length=200)),
                ('conteudo_postagem', models.TextField()),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor_postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_post',
            fields=[
                ('id_perfil_post', models.AutoField(primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.perfil')),
                ('id_postagem', models.ForeignKey(db_column='id_postagem', on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='socialapp.postagem')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id_telefone', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telefone', models.CharField(max_length=255)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='socialapp.postagem')),
            ],
            options={
                'unique_together': {('post', 'usuario')},
            },
        ),
    ]
