# Generated by Django 5.2 on 2025-06-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='id_avalia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialapp.avalia'),
        ),
    ]
