# Generated by Django 5.2 on 2025-06-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_postagem_id_avalia'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='tags_sugeridas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avalia',
            name='valor_avalia',
            field=models.CharField(max_length=255, verbose_name='Avaliação'),
        ),
    ]
